In [ ]:
import sgd
import numpy as np
from lib import algorithms

quadratic = sgd.Polynomial(3)

dataset_parameters = np.array([4, 3, 2, 1])  # y = 4 + 3x + 2x^2 + x^3

dataset = [(np.array([x]), quadratic(dataset_parameters, np.array([x]))) for x in np.linspace(-2, 2, 500)]
reg = sgd.L1Regularization(0)
ef = sgd.ErrorFunc(quadratic, reg, dataset)
epochs = 100
batch_size = 10
lr_c = algorithms.lr_constant(0.01);
momentum = 0.9

res = sgd.sgd(quadratic, reg, dataset, epochs=epochs, batch_size=batch_size, lr=lr_c)
print(res, ef(res))
res_m = sgd.sgd(quadratic, reg, dataset, epochs=epochs, batch_size=batch_size, lr=lr_c, momentum=momentum)
print(res_m, ef(res_m))
res2 = sgd.torch_sgd(dataset, degree=3, epochs=epochs, batch_size=batch_size, lr=0.01, optimizer_type='SGD_Momentum', momentum=momentum)
print(res2, ef(res2))

[2.80143361 1.37486804 2.51623783 1.50062098] 1.245475267410994
[4.04386003 3.06773605 2.09265124 0.97619562] 0.041476774064081956


c:\Users\denzu\OneDrive\Desktop\metopt\metopt-lab1\sgd\__init__.py:107: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:257.)
  X = torch.tensor([x[0] for x in dataset], dtype=torch.float32)


[1.9235908 2.9999995 2.0000002 1.0000001] 4.311473926352935
